# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.ticketblock.com:
    container_name: orderer.ticketblock.com
    image: hyperledger/fabric-orderer
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_KAFKA_TOPIC_REPLICATIONFACTOR=1
      - ORDERER_KAFKA_VERBOSE=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/ticketblock.com/orderers/orderer.ticketblock.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/ticketblock.com/orderers/orderer.ticketblock.com/tls/:/var/hyperledger/orderer/tls
    - orderer.ticketblock.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.org_ticketblock.ticketblock.com:
    container_name: peer0.org_ticketblock.ticketblock.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org_ticketblock.ticketblock.com
      - CORE_PEER_ADDRESS=peer0.org_ticketblock.ticketblock.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org_ticketblock.ticketblock.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org_ticketblock.ticketblock.com:7051
      - CORE_PEER_LOCALMSPID=OrgTicketBlockMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org_ticketblock.ticketblock.com/peers/peer0.org_ticketblock.ticketblock.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org_ticketblock.ticketblock.com/peers/peer0.org_ticketblock.ticketblock.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org_ticketblock.ticketblock.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053


  peer0.org_promotor1.ticketblock.com:
    container_name: peer0.org_promotor1.ticketblock.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org_promotor1.ticketblock.com
      - CORE_PEER_ADDRESS=peer0.org_promotor1.ticketblock.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org_promotor1.ticketblock.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org_promotor1.ticketblock.com:7051
      - CORE_PEER_LOCALMSPID=OrgPromotor1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org_promotor1.ticketblock.com/peers/peer0.org_promotor1.ticketblock.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org_promotor1.ticketblock.com/peers/peer0.org_promotor1.ticketblock.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org_promotor1.ticketblock.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053

  