NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.org_promotor1.ticketblock.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.org_promotor1.ticketblock.com-cert.pem
    OrganizationalUnitIdentifier: peer
